### ISSUE TITLE
Design-Seeds.com palette images raise 'incorrect sRGB profile' warning with url_palette()

### ISSUE THREAD

**Issue by DesiQuintans** [EmilHvitfeldt/quickpalette#1]
Hi, love the package! Thought it would be helpful to let you know that palette images from design-seeds.com DO work with quickpalette, but they raise an error:

```
> url <- "https://www.design-seeds.com/wp-content/uploads/2018/02/2_21_ColorPlay_caroline.png"
> url_palette(url, n_clusters = 6)

[1] "#FDE9AF" "#B5E7FE" "#75C4F8" "#3F6BC0" "#DBF5FE" "#2B4171"
Warning message:
In png::readPNG(RCurl::getURLContent(url)) :
  libpng warning: iCCP: known incorrect sRGB profile 
```

As you can see, the palette is still generated, but so is a warning message. This is actually a non-issue because design-seeds also provide the hex codes and quickpalette can parse them from a straight copy-paste:

```
> seed <- "#FCE8AE
+ #2B4071
+ #3F6ABF
+ #75C3F8
+ #B4E7FD
+ #DAF5FD"
> regex_palette(seed)

[1] "#FCE8AE" "#2B4071" "#3F6ABF" "#75C3F8" "#B4E7FD" "#DAF5FD"
```

But maybe you'll want to suppress some warnings, I don't know!

**Comment by EmilHvitfeldt** [comment]
Thank you for making me aware of the issue! 

The problem appears to be with Libpng-1.6 (which is used by the `png` package) is more stringent about checking ICC profiles than previous versions. As you have noticed it will still work as intended. 

I am generally hesitant to add warning suppression, but in this case I have added an option to do so. 

For your particular example, I will point out to you that the palette you got using `url_palette` and `regex_palette` are not identical since the the image have more colors the the 5 shown which have skewed the palette very so slightly.
